# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt-get update \
    && apt-get -y install sudo strace curl cmake pkg-config python libssl-dev llvm-dev libz-dev gnuplot-nox \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  displayName: 'Install Rust Nightly'

- script: |
    cargo build release    
  displayName: 'Cargo build'
